name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Adjust if you are using a different version

      - name: Build the solution
        run: dotnet build CardValidation.sln --configuration Release

      - name: Run unit tests
        run: dotnet test UnitTests/UnitTests.csproj --configuration Release --no-build --verbosity normal

      - name: Build Docker image for integration tests
        run: |
          docker build -t cardvalidation-integration-tests -f CardValidation.Web/Dockerfile .

      - name: Run integration tests inside Docker
        run: |
          docker run --rm cardvalidation-integration-tests dotnet test IntegrationTests/IntegrationTests.csproj --no-build --logger:trx

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: **/*.trx
