name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and run unit tests
        run: |
          dotnet build CardValidation.sln --configuration Release
          dotnet test UnitTests/UnitTests.csproj

      - name: Build Docker images
        run: |
          docker build -t card-validation-api -f CardValidation.Web/Dockerfile .
          docker build -t card-validation-integration-tests -f Dockerfile.integration-tests .

      - name: Run integration tests
        run: |
          docker-compose up --abort-on-container-exit --build
